# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: apidb
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipass
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"